---
name: Call a reusable workflow

on: push

jobs:
 dependency-review:
  uses: cisagov/github-actions-workflows/.github/workflows/dependency-review.yml@first-commits
 codeql-analysis:
  uses: cisagov/github-actions-workflows/.github/workflows/codeql-analysis.yml@first-commits
